version: "3"

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  backend-dev:
    container_name: backend-dev
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "8080"

  nginx:
    depends_on:
      - backend-dev
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./config/nginx
    ports:
      - "80:80"