# common
server:
  servlet:
    context-path: /api
  forward-headers-strategy: framework

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  token:
    secret: ${JWT_SECRET}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        database-platform: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

## TODO : 세부 설정 dev, prod 나누기
---
# dev
spring:
  config:
    activate:
      on-profile: dev


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

---
# prod
spring:
  config:
    activate:
      on-profile: prod

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace